### ISSUE TITLE
[Bug]: Error when trying to install

### ISSUE THREAD

**Issue by ayrtondenner** [deepgram-devs/deepgram-cli#127]
### What happened?

When I try to install the lib via "npm install -g @deepgram/cli", I get the following 404 error message: Not Found - GET https://registry.npmjs.org/@deepgram%2fcli - Not found

### Relevant log output

```shell
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@deepgram%2fcli - Not found
npm ERR! 404
npm ERR! 404  '@deepgram/cli@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lukeocodes** [comment]
What command did you use exactly? Exactly as you put it there?

**Comment by ayrtondenner** [comment]
I was trying to install using "npm install -g @deepgram/cli" in the console.

**Comment by lukeocodes** [comment]
Yikes that was my fault! It should now be fixed! (I forgot it was still private)

https://www.npmjs.com/package/@deepgram/cli
